Repository rustwasm/wasm-bindgen, pull requests merged in 2023-08, with the labels that each got.

#3537 Changed `write` functions of FileSystemSyncAccessHandle to accept immutable buffers
  CHANGELOG.md
  crates/web-sys/src/features/gen_FileSystemSyncAccessHandle.rs
  crates/web-sys/src/features/gen_FileSystemWritableFileStream.rs
  crates/web-sys/src/features/gen_IdbFileHandle.rs
  crates/web-sys/tests/wasm/whitelisted_immutable_slices.rs
  crates/webidl/src/constants.rs
Labels: breaking-change

#3544 Add `cargo-binstall` support to `wasm-bindgen`
  CHANGELOG.md
  README.md
  crates/cli/Cargo.toml
Labels: waiting for author

#3233 Disable support for `wasm32-wasi`
  CHANGELOG.md
  crates/backend/src/codegen.rs
  src/lib.rs
Labels: waiting for author

#3535 Add missing CSS loaders for todomvc app
  _package.json
  examples/todomvc/index.html
  examples/todomvc/index.js
  examples/todomvc/package.json
  examples/todomvc/webpack.config.js
Labels: needs review

#3562 Remove class wrap for constructors in Rust exports
  CHANGELOG.md
  crates/cli-support/src/js/binding.rs
  crates/cli-support/src/wit/mod.rs
  crates/cli/tests/reference/builder.d.ts
  crates/cli/tests/reference/builder.js
  crates/cli/tests/reference/builder.rs
  crates/cli/tests/reference/builder.wat
  crates/cli/tests/reference/constructor.d.ts
  crates/cli/tests/reference/constructor.js
  crates/cli/tests/reference/constructor.rs
  crates/cli/tests/reference/constructor.wat
  crates/cli/tests/wasm-bindgen/main.rs
  guide/src/reference/attributes/on-rust-exports/constructor.md
Labels: waiting for author
